// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARzK8kAYx56uWCpytYHdAVmuTNsSMBnCI',
    appId: '1:606219388707:web:2a400bcd5cf04d1b632e96',
    messagingSenderId: '606219388707',
    projectId: 'story-board-49122',
    authDomain: 'story-board-49122.firebaseapp.com',
    storageBucket: 'story-board-49122.firebasestorage.app',
    measurementId: 'G-Z0Q45M57TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZTKSP5Xqo0L1w-j3RNv7bj7W1QJKbcxw',
    appId: '1:606219388707:android:eb4a64028b04e4f4632e96',
    messagingSenderId: '606219388707',
    projectId: 'story-board-49122',
    storageBucket: 'story-board-49122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoES_ssiiQYJ3c-1sDtOtspO-0L-wUAIs',
    appId: '1:606219388707:ios:e8147cd910d4f8ab632e96',
    messagingSenderId: '606219388707',
    projectId: 'story-board-49122',
    storageBucket: 'story-board-49122.firebasestorage.app',
    iosBundleId: 'com.example.storyBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoES_ssiiQYJ3c-1sDtOtspO-0L-wUAIs',
    appId: '1:606219388707:ios:e8147cd910d4f8ab632e96',
    messagingSenderId: '606219388707',
    projectId: 'story-board-49122',
    storageBucket: 'story-board-49122.firebasestorage.app',
    iosBundleId: 'com.example.storyBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARzK8kAYx56uWCpytYHdAVmuTNsSMBnCI',
    appId: '1:606219388707:web:667b0d83592644e6632e96',
    messagingSenderId: '606219388707',
    projectId: 'story-board-49122',
    authDomain: 'story-board-49122.firebaseapp.com',
    storageBucket: 'story-board-49122.firebasestorage.app',
    measurementId: 'G-1L4R00HJSM',
  );
}
